#
# DO NOT Edit this file. Canonical version of fun lives in the repo's package.json. This file is generated
# by a grunt task when the standalone release is built.
#
module fun
  module Core
    VERSION = "2.2.1"
  end
end
